name: Sync images

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sync:
    name: Sync images
    runs-on: ubuntu-latest
    steps:
      - name: 'Sync images'
        run: |
          timestamp=$(date +%s)
          curl -X 'POST' \
            'https://api.cnb.cool/spotty/sync-images/-/build/start' \
            -H 'accept: application/json' \
            -H "Authorization: Bearer ${{ secrets.CNB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '{
            "branch": "main",
            "event": "api_trigger_by_cdm",
            "env":{"build_time":"${timestamp}"}
          }'
