name: Sync images

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sync:
    name: Sync images
    # runs-on: ubuntu-latest
    runs-on: hongkong
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: 'Set up skopeo'
        uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest

      - name: 'Sync images'
        run: |
          skopeo --version
